// packages/vue/src/widgets/ComponentTreeWidget/index.tsx
import { Engine, GlobalRegistry, TreeNode } from '@pind/designable-core'
import { observer } from '@formily/reactive-vue'
import {
  computed,
  defineComponent,
  Fragment,
  h,
  PropType,
  provide,
  watch,
} from 'vue'
import {
  DesignerComponentsContext,
  DesignerEngineContext,
  TreeNodeContext,
} from '../../context'
import { useComponents, useDesigner } from '../../hooks'
import { IDesignerComponents } from '../../types'

export const TreeNodeWidget = observer(
  defineComponent({
    name: 'TreeNodeWidget',
    props: {
      node: {
        type: Object as PropType<TreeNode>,
        required: true,
      },
    },
    setup(props) {
      const designer = useDesigner()
      const components = useComponents()
      const nodeRef = computed(() => props.node)
      provide(TreeNodeContext, nodeRef)

      return () => {
        const node = props.node
        const renderChildren = () => {
          if (node?.designerProps?.selfRenderChildren) return []
          return node?.children?.map((child) => {
            return h(TreeNodeWidget, { node: child, key: child.id })
          })
        }

        const renderProps = (extendsProps: any = {}) => {
          const props = {
            ...node.designerProps?.defaultProps,
            ...extendsProps,
            ...node.props,
            ...node.designerProps?.getComponentProps?.(node),
          }
          if (node.depth === 0) {
            delete props.style
          }
          return props
        }

        const renderComponent = () => {
          const componentName = node.componentName
          const Component = components.value?.[componentName]
          const dataId = {}
          if (Component) {
            if (designer.value) {
              dataId[designer.value.props?.nodeIdAttrName] = node.id
            }
            return h(Component, renderProps(dataId), {
              default: renderChildren,
            })
          } else {
            if (node?.children?.length) {
              return h(Fragment, renderChildren())
            }
          }
        }
        if (!node) return null
        if (node.hidden) return null
        return h(Fragment, [renderComponent()])
      }
    },
  })
)

export const ComponentTreeWidget = observer(
  defineComponent({
    name: 'ComponentTreeWidget',
    props: {
      components: {
        type: Object as PropType<IDesignerComponents>,
        required: true,
      },
      tree: {
        type: Object as PropType<TreeNode>,
        required: true,
      },
      designer: {
        type: Object as PropType<Engine>,
        required: true,
      },
    },
    setup(props) {
      const treeRef = computed(() => props.tree)
      provide(TreeNodeContext, treeRef)
      const componentsRef = computed(() => props.components)
      provide(DesignerComponentsContext, componentsRef)
      const designerRef = computed(() => props.designer)
      provide(DesignerEngineContext, designerRef)
      watch(
        () => props.components,
        () => {
          GlobalRegistry.registerDesignerBehaviors(props.components)
        },
        { immediate: true }
      )
      return () => {
        const { tree } = props

        return h(Fragment, null, [h(TreeNodeWidget, { node: tree })])
      }
    },
  })
)

// packages/react/src/widgets/ComponentTreeWidget/index.tsx
import React, { Fragment, useEffect } from 'react'
import { useTree, usePrefix, useDesigner, useComponents } from '../../hooks'
import { TreeNodeContext, DesignerComponentsContext } from '../../context'
import { IDesignerComponents } from '../../types'
import { TreeNode, GlobalRegistry } from '@pind/designable-core'
import { observer } from '@formily/reactive-react'
import cls from 'classnames'
import './styles.less'

export interface IComponentTreeWidgetProps {
  style?: React.CSSProperties
  className?: string
  components: IDesignerComponents
}

export interface ITreeNodeWidgetProps {
  node: TreeNode
  children?: React.ReactChild
}

export const TreeNodeWidget: React.FC<ITreeNodeWidgetProps> = observer(
  (props: ITreeNodeWidgetProps) => {
    const designer = useDesigner(props.node?.designerProps?.effects)
    const components = useComponents()
    const node = props.node
    const renderChildren = () => {
      if (node?.designerProps?.selfRenderChildren) return []
      return node?.children?.map((child) => {
        return <TreeNodeWidget key={child.id} node={child} />
      })
    }
    const renderProps = (extendsProps: any = {}) => {
      const props = {
        ...node.designerProps?.defaultProps,
        ...extendsProps,
        ...node.props,
        ...node.designerProps?.getComponentProps?.(node),
      }
      if (node.depth === 0) {
        delete props.style
      }
      return props
    }
    const renderComponent = () => {
      const componentName = node.componentName
      const Component = components[componentName]
      const dataId = {}
      if (Component) {
        if (designer) {
          dataId[designer?.props?.nodeIdAttrName] = node.id
        }
        return React.createElement(
          Component,
          renderProps(dataId),
          ...renderChildren()
        )
      } else {
        if (node?.children?.length) {
          return <Fragment>{renderChildren()}</Fragment>
        }
      }
    }

    if (!node) return null
    if (node.hidden) return null
    return React.createElement(
      TreeNodeContext.Provider,
      { value: node },
      renderComponent()
    )
  }
)

export const ComponentTreeWidget: React.FC<IComponentTreeWidgetProps> =
  observer((props: IComponentTreeWidgetProps) => {
    const tree = useTree()
    const prefix = usePrefix('component-tree')
    const designer = useDesigner()
    const dataId = {}
    if (designer && tree) {
      dataId[designer?.props?.nodeIdAttrName] = tree.id
    }
    useEffect(() => {
      GlobalRegistry.registerDesignerBehaviors(props.components)
    }, [])
    return (
      <div
        style={{ ...props.style, ...tree?.props?.style }}
        className={cls(prefix, props.className)}
        {...dataId}
      >
        <DesignerComponentsContext.Provider value={props.components}>
          <TreeNodeWidget node={tree} />
        </DesignerComponentsContext.Provider>
      </div>
    )
  })

ComponentTreeWidget.displayName = 'ComponentTreeWidget'
